# Generated by Django 2.0.5 on 2019-01-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
