# Generated by Django 2.0.5 on 2018-11-29 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Cook', 'COOK'), ('Client', 'CLIENT'), ('Delivery Point', 'DELIVERY POINT')], max_length=20)),
                ('profile_image', models.ImageField(upload_to='images')),
                ('contact_no', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_area.Area')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
