# Generated by Django 2.0.5 on 2018-11-29 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_users_profile', '0001_initial'),
        ('food_delivery', '0001_initial'),
        ('food_area', '0001_initial'),
        ('food_items', '0001_initial'),
        ('food_providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_image', models.ImageField(upload_to='images')),
                ('client_contact_no', models.PositiveIntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_area.Area')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_users_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_area.Area')),
                ('client_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_order.Client')),
                ('delivery_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_delivery.DeliveryPoint')),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_items.FoodItems')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_providers.CooKInfo')),
            ],
        ),
    ]
