# Generated by Django 2.0.5 on 2019-01-24 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0002_auto_20190124_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_order.Client'),
        ),
    ]
